"""Regenerate shader contour constants from the attributed, bundled profiles."""
from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
j=json.loads((root/'Resources/ClaudeBuildingMotion.json').read_text())
profiles=j['profiles'];n=j['segments'];frames=j['frames']
assert len(profiles)==frames and all(len(row)==n for row in profiles)
values='\n'.join(','.join(f'{x:.6f}' for x in row)+',' for row in profiles)
mean=','.join(f'{sum(row[i] for row in profiles)/frames:.6f}' for i in range(n))
block=f'''// BEGIN CLAUDE BUILDING MOTION
// Reference-derived silhouette. See NOTICE; generated by scripts/generate_claude_motion.py.
constant float claudeContour[{n*frames}]={{
{values}
}};
constant float claudeMeanContour[{n}]={{{mean}}};
// END CLAUDE BUILDING MOTION'''
p=root/'Resources/Cosmos.metal';s=p.read_text();s,count=re.subn(r'// BEGIN CLAUDE BUILDING MOTION.*?// END CLAUDE BUILDING MOTION',lambda _:block,s,flags=re.S);assert count==1;p.write_text(s)
print('Regenerated contour constants from bundled profiles')
